feat: Api (2)
ietf-tools/rfced-www pull request #20
Opened 2024-12-01 23:17 UTC by holloway

supercedes #11 

Implements the OpenAPI generator/client for Red.

2024-12-09 15:39 UTC, jennifer-richards reviewed
Looks generally good. A couple minor comments inline - the "names" of RFC docs should be "RFC 1234" with a non-breaking space. I flagged it where I noticed but don't know if I caught everywhere. We could consider bringing back the name field to the API response schema and avoid peppering that formatting rule throughout the front end. Not sure how that balances against including effectively redundant information in the schema.

Holding off on actually approving to get @rjsparks feedback about whether we want to move forward with this or wait until we progress a bit further on returning authoritative author info in the Red API. (My own preference would be to merge this and the datatracker side of the API so that we can move forward - I think we all understand that it's still under development)

2024-12-09 15:39 UTC, jennifer-richards commented on client/pages/search.vue
> +                :title="`RFC${searchResult.number}`"
I believe the canonical format has a space after "RFC". I.e., "RFC 1234" rather than "RFC1234"

2024-12-09 15:39 UTC, jennifer-richards commented on client/components/RFCCardSearchItem.vue
> +    :title="`RFC${props.searchItem.number}`"
Again should have a space between "RFC" and the number ("RFC 1234")

2024-12-09 18:39 UTC, rjsparks commented
I did merge (but have not yet released/deployed) the API that populates just on datatracker data - that will evolve into something that also reaches into purple.

2024-12-09 18:44 UTC, rjsparks commented
@ghwood, @alexisannerossi - please note the discussion about the presentation of RFC numbers

2024-12-10 06:29 UTC, holloway commented
I'll add a helper for formatting 'RFC number' so that it's consistent across the site.

2024-12-10 20:52 UTC, holloway commented
Done

2024-12-10 21:34 UTC, holloway commented
Ready for review again now

2024-12-10 22:07 UTC, jennifer-richards requested changes
I'm a little surprised by the approach to converting an RFC num to a title by first constructing a "wrong" format, parsing it, and converting it to the "right" one. I suppose it has the benefit that it'll continue to work if we have other sources of RFC titles that aren't as convenient as the bare number and can deal with things that are STD / BCP.

I don't think we need to be counting CPU cycles and we'll need to refactor things when we start talking about subseries (bcp, std, etc), so not opposed. As noted inline, I think it'll misbehave if handed a name like "RFC 1234" that already has the space, so I think that should be fixed.

Also a question about `\xa0`

2024-12-10 22:07 UTC, jennifer-richards commented on client/components/rfc.ts
> +const NonBreakingSpace = '\xa0'
Is an `&nbsp;` entity an option instead of an explicit value?

2024-12-10 22:07 UTC, jennifer-richards commented on client/components/rfc.ts
> +  return `${parts.type}${NonBreakingSpace}${parts.number}`
If I read the code for `parseRFCId` correctly, I think this will act funny if a title already has the space. I.e., `formatTitlePlaintext('RFC 1234')` will give `RFC \xa01234`. That seems like an undesirable property.

2024-12-10 23:08 UTC, holloway commented on client/components/rfc.ts
> +const NonBreakingSpace = '\xa0'
Unfortunately not, as the `h()` function escapes strings...

![Screenshot from 2024-12-11 12-06-26](https://github.com/user-attachments/assets/e4f48b95-2eb9-424e-ad34-0947be9c7a20)

...and afaik HTML entities are only possible using an `innerHTML` which we probably don't want

2024-12-10 23:10 UTC, holloway commented on client/components/rfc.ts
> +  return `${parts.type}${NonBreakingSpace}${parts.number}`
Correct, it's not able to parse the formatted version (in plaintext or `h()` aka `VNode`). I could add support for plaintext parsing though.

2024-12-10 23:11 UTC, holloway commented
@jennifer-richards 

>  other sources of RFC titles that aren't as convenient as the bare number and can deal with things that are STD / BCP.

Yep that was my thinking for paths like https://rfc-editor.org/info/std96

2024-12-10 23:16 UTC, holloway commented
@jennifer-richards does the API provide the abstract?

2024-12-11 00:27 UTC, jennifer-richards commented
> Should the search engine return results for `std*` like that?

I suspect the answer will be yes but we'll see. We'll need to think about what the api response should look like in those cases.

2024-12-11 00:28 UTC, jennifer-richards commented
> @jennifer-richards does the API provide the abstract?

Yes, I believe so. I added it not long before the PR was merged so you may have grabbed a version before it did so.

2024-12-11 00:38 UTC, jennifer-richards commented on client/components/rfc.ts
> +  return `${parts.type}${NonBreakingSpace}${parts.number}`
Ok. I guess I wonder whether a more explicit construction of the `parts` array when you know the components would be cleaner than building, then parsing a string. I'll yield to your judgement about what better fits the project and what methods will be more useful, though.

2024-12-11 22:41 UTC, holloway commented
@jennifer-richards I've added the 'abstract' now. `parseRfcId` now handles whitespace (including non-breaking spaces) and there's some unit tests to verify that

2024-12-12 01:30 UTC, jennifer-richards submitted a review, later dismissed
LGTM

2024-12-12 01:36 UTC, jennifer-richards approved these changes
LGerTM

2024-12-12 01:41 UTC, merged